import type { Config } from 'tailwindcss';

// Design tokens ported from the Stitch "UnicornTail — Obsidian Prism (blue
// re-skin)" design system. These semantic Material-style names are the shared
// contract for every screen (Landing, Login, Editor Workspace). Colours are the
// dark theme; `darkMode: "class"` + <html class="dark"> keeps room for a future
// light theme without renaming tokens.
const config: Config = {
  darkMode: 'class',
  content: [
    './src/app/**/*.{ts,tsx}',
    './src/components/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#051424',
        'surface-dim': '#051424',
        surface: '#051424',
        'surface-bright': '#2c3a4c',
        'surface-container-lowest': '#010f1f',
        'surface-container-low': '#0d1c2d',
        'surface-container': '#122131',
        'surface-container-high': '#1c2b3c',
        'surface-container-highest': '#273647',
        'surface-variant': '#273647',
        'surface-tint': '#85d3dc',
        primary: '#ffffff',
        'primary-container': '#a1eff8',
        'primary-fixed': '#a1eff8',
        'primary-fixed-dim': '#85d3dc',
        'inverse-primary': '#026971',
        'on-primary': '#00363b',
        'on-primary-container': '#126f77',
        'on-primary-fixed': '#002023',
        'on-primary-fixed-variant': '#004f55',
        secondary: '#c8c2e9',
        'secondary-container': '#494566',
        'secondary-fixed': '#e5deff',
        'secondary-fixed-dim': '#c8c2e9',
        'on-secondary': '#302c4b',
        'on-secondary-container': '#bab4da',
        'on-secondary-fixed': '#1b1735',
        'on-secondary-fixed-variant': '#474363',
        tertiary: '#ffffff',
        'tertiary-container': '#dee2ec',
        'tertiary-fixed': '#dee2ec',
        'tertiary-fixed-dim': '#c2c7d0',
        'on-tertiary': '#2c3138',
        'on-tertiary-container': '#60656d',
        'on-tertiary-fixed': '#171c23',
        'on-tertiary-fixed-variant': '#42474f',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'on-surface': '#d4e4fa',
        'on-surface-variant': '#bec8ca',
        'on-background': '#d4e4fa',
        'inverse-surface': '#d4e4fa',
        'inverse-on-surface': '#233143',
        outline: '#889394',
        'outline-variant': '#3f494a',
        // Editor Workspace gradient stops.
        'accent-gradient-start': '#85d3dc',
        'accent-gradient-end': '#c8c2e9',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        unit: '4px',
        gutter: '16px',
        'margin-mobile': '16px',
        'margin-desktop': '48px',
      },
      fontFamily: {
        display: ['var(--font-geist)', 'sans-serif'],
        'headline-lg': ['var(--font-geist)', 'sans-serif'],
        'headline-md': ['var(--font-geist)', 'sans-serif'],
        'body-lg': ['var(--font-geist)', 'sans-serif'],
        'body-md': ['var(--font-geist)', 'sans-serif'],
        'label-md': ['var(--font-jetbrains-mono)', 'monospace'],
        'label-sm': ['var(--font-jetbrains-mono)', 'monospace'],
      },
      fontSize: {
        display: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};

export default config;
